[package]
# Metadata that is also used to generate the --help command:
name = "application"
version = "0.0.1"
authors = ["Daniel Schemmel"]
description = "A sample application"

# Other metadata
edition = "2018"
publish = false

[features]
default = []
bug = []
subcommands = []

[dependencies]
failure = "0.1"
flexi_logger = { version = "0.13", features = ["ziplogs"] }
log = "0.4"
structopt = { version = "0.3", git = "https://github.com/TeXitoi/structopt", branch = "master" }
